# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"+\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\toperation\x18\x02 \x01(\t\"\x97\x01\n\x12\x41ppendEntryRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"4\n\x13\x41ppendEntryResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x32~\n\x08RaftNode\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12\x38\n\x0b\x41ppendEntry\x12\x13.AppendEntryRequest\x1a\x14.AppendEntryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGENTRY']._serialized_start=14
  _globals['_LOGENTRY']._serialized_end=57
  _globals['_APPENDENTRYREQUEST']._serialized_start=60
  _globals['_APPENDENTRYREQUEST']._serialized_end=211
  _globals['_APPENDENTRYRESPONSE']._serialized_start=213
  _globals['_APPENDENTRYRESPONSE']._serialized_end=265
  _globals['_REQUESTVOTEREQUEST']._serialized_start=267
  _globals['_REQUESTVOTEREQUEST']._serialized_end=370
  _globals['_REQUESTVOTERESPONSE']._serialized_start=372
  _globals['_REQUESTVOTERESPONSE']._serialized_end=429
  _globals['_RAFTNODE']._serialized_start=431
  _globals['_RAFTNODE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
